# Generated by Django 4.2.13 on 2024-07-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='rented_time',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
