# Generated by Django 4.2.13 on 2024-07-03 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bikes', '0002_bike_rented_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='rented_at',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='rented_time',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='renter',
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.bike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
