# Generated by Django 4.2.13 on 2024-07-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_remove_bike_price_remove_bike_rented_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'Аренда'},
        ),
    ]
