# Generated by Django 4.2.13 on 2024-07-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_alter_rental_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'Аренда велосипедов'},
        ),
    ]
